In [1]:
import string
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from nltk.stem import WordNetLemmatizer
from nltk import sent_tokenize
from nltk.corpus import stopwords

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english') + [word.strip("\n") for word in open("remove_words.txt", "r")])

In [2]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 2087-A02D

 Directory of C:\Users\Administrator\Desktop\Document-Similarity

12/01/2022  11:38 AM    <DIR>          .
11/10/2022  02:45 PM    <DIR>          ..
11/30/2022  02:18 PM    <DIR>          .ipynb_checkpoints
11/16/2022  03:10 PM           391,697 all_articles.csv
12/01/2022  11:38 AM    <DIR>          archive
11/22/2022  10:49 AM            19,471 base_matrix.png
11/29/2022  11:25 AM             5,967 bert_similarity.py
11/30/2022  11:08 PM            66,810 Classifier.ipynb
11/30/2022  11:44 AM             1,610 cosine_similarity_test.py
11/16/2022  04:19 PM    <DIR>          doc2vec
11/22/2022  10:00 AM             7,241 doc2vec_similarity.py
11/22/2022  10:36 AM           435,172 doc2vec_tokenized_articles.csv
11/23/2022  10:30 AM             4,124 evaluate_model.py
11/21/2022  10:50 AM    <DIR>          experiments
12/01/2022  11:43 AM            10,478 extract_bert_embeddings.py
11/07/2022  11:14 AM    <DIR>          factiva_articles
11/07/2022  11:14 AM           165,938 Fin_Wellbeing_subsample.xlsx
12/01/2022  11:44 AM             1,321 irrelevant_test.csv
12/01/2022  11:43 AM           145,285 irrelevant_words_count.csv
11/30/2022  02:30 PM             6,740 jaccard_similarity.py
11/30/2022  12:00 PM            19,749 Load relevant df.ipynb
11/29/2022  11:25 AM            76,131 output.csv
11/16/2022  03:10 PM             7,869 preprocess_factiva_articles.py
11/29/2022  03:07 PM             9,814 Relevant word df test.ipynb
12/01/2022  11:43 AM             1,336 relevant_test.csv
12/01/2022  11:43 AM           146,418 relevant_words_count.csv
11/29/2022  11:25 AM               121 remove_words.txt
11/07/2022  11:14 AM    <DIR>          reqs
11/07/2022  11:14 AM                13 requirements.txt
11/29/2022  11:25 AM    <DIR>          results
11/21/2022  03:35 PM             5,382 tf_idf_similarity.py
11/16/2022  03:29 PM    <DIR>          use
11/21/2022  03:59 PM             5,631 use_similarity.py
11/07/2022  12:52 PM    <DIR>          wmd
11/22/2022  10:41 AM             5,466 wmd_similarity.py
11/08/2022  11:43 AM    <DIR>          __pycache__
              24 File(s)      1,539,784 bytes
              12 Dir(s)  18,788,962,304 bytes free

In [3]:
articles_df = pd.read_csv('all_articles.csv', usecols = ['article_title','text','relevant_campbell','relevant_kristen','mismatch'])

In [4]:
articles_df

,article_title,text,relevant_campbell,relevant_kristen,mismatch
0,Intervention was the right thing to do,News Intervention was the right thing to do FI...,0,0,0
1,SIX STATES FILE A CHALLENGE TO THE BIDEN ADMIN...,SIX STATES FILE A CHALLENGE TO THE BIDEN ADMIN...,0,0,0
2,Senator Reverend Warnock Introduces Bill to En...,Senator Reverend Warnock Introduces Bill to En...,1,0,1
3,10 Markets Where Sellers Are Cutting Home Pric...,Daily 10 Markets Where Sellers Are Cutting Hom...,1,1,0
4,"Biden touts Inflation Reduction Act, critics s...","Biden touts Inflation Reduction Act, critics s...",0,1,1
...,...,...,...,...,...
122,Jobs & Money - Women stand to get a better deal.,Jobs & Money - Women stand to get a better dea...,1,1,0
123,Pension off AVC rules; The Last Word,Pension off AVC rules; The Last Word THE G...,0,1,1
124,"Gold Stocks Favoured As Telecom, Bank Shares Fall",Business; Money Market And Share Market Gold S...,0,0,0
125,Wall of silence over 'flexible' Abbey fund,Wall of silence over 'flexible' Abbey fund ...,0,1,1
126,Million-dollar Partners,"Money Million-dollar Partners ""You do need the...",1,1,0

In [5]:
relevant_df = pd.read_csv("relevant_test.csv", usecols = ['word','frequency','frequency_scaled','relevancy_score','weighted_score'])
relevant_df

          word  frequency  frequency_scaled  relevancy_score  weighted_score
0   retirement        131          0.828025        10.886148        9.014008
1       income         69          0.433121        12.111348        5.245679
2     interest         59          0.369427        13.518146        4.993965
3       worker         61          0.382166        11.943562        4.564418
4         home         65          0.407643        11.086713        4.519425
5       credit         57          0.356688        12.019035        4.287044
6         need         56          0.350318        12.227023        4.283352
7         cost         50          0.312102        13.036452        4.068702
8       health         58          0.363057        11.065419        4.017381
9         help         48          0.299363        13.187963        3.947989
10         age         46          0.286624        11.952712        3.425937
11        many         47          0.292994        11.647051        3.412512
12       still         46          0.286624        11.790719        3.379506
13        take         40          0.248408        13.431594        3.336511
14      scheme         39          0.242038        13.579039        3.286646
15        want         40          0.248408        13.165342        3.270372
16       woman         45          0.280255        11.511510        3.226156
17     benefit         42          0.261146        12.321045        3.217598

In [6]:
irrelevant_df = pd.read_csv("irrelevant_test.csv",  usecols = ['word','frequency','frequency_scaled','relevancy_score','weighted_score'])
irrelevant_df

         word  frequency  frequency_scaled  relevancy_score  weighted_score
0      market         70          0.726316        11.760501        8.541838
1        deal         60          0.621053        12.929773        8.030070
2     company         53          0.547368        13.653391        7.473435
3        bank         58          0.600000        11.542281        6.925368
4        bond         52          0.536842        12.752490        6.846074
5    customer         48          0.494737        11.498784        5.688872
6        sale         38          0.389474        13.426186        5.229146
7       share         34          0.347368        13.301644        4.620571
8       group         35          0.357895        12.804445        4.582643
9        well         32          0.326316        12.894478        4.207672
10      offer         30          0.305263        13.213309        4.033536
11     estate         32          0.326316        12.160165        3.968054
12      point         28          0.284211        13.192139        3.749345
13    product         28          0.284211        13.073472        3.715618
14   investor         32          0.326316        11.329690        3.697057
15  insurance         29          0.294737        11.191980        3.298689
16   business         29          0.294737        10.814732        3.187500
17       week         28          0.284211         9.573377        2.720855

In [7]:
articles_df['predicted'] = np.ones(len(articles_df))
all_articles_relevancy = {}
for index, row in articles_df.iterrows():
    
    #if index == 0:
    all_articles_relevancy[row['article_title']] = 0
    sentences = sent_tokenize(row['text'])

    for sentence in sentences:
        words_in_sentence = list(sentence.split(" "))
        for word_ in words_in_sentence:

            word_ = word_.lower()
            word_ = word_.strip()
            word_ = word_.replace(" ", "")
            word_ = word_.replace(",", "")
            word_ = word_.replace(".", "")
            word_ = word_.replace(":", "")
            word_ = word_.replace("/", "")
            word_ = word_.replace("-", "")
            word_ = word_.replace("(", "")
            word_ = word_.replace(")", "")

            if lemmatizer.lemmatize(word_) != 'ha' and lemmatizer.lemmatize(word_) != 'wa':
                word_ = lemmatizer.lemmatize(word_)

            if word_ not in stop_words and word_ not in string.punctuation:

                if word_ in list(relevant_df['word']):
                    #print("RELEVANT WORD")
                    #print(word_)
                    all_articles_relevancy[row['article_title']] += float(relevant_df[relevant_df['word'] == word_]['weighted_score'])
                    #print(all_articles_relevancy['article_title'])

                if word_ in list(irrelevant_df['word']):
                    #print("IRRELEVANT WORD")
                    #print(word_)
                    all_articles_relevancy[row['article_title']] -= float(irrelevant_df[irrelevant_df['word'] == word_]['weighted_score'])
                    #print(all_articles_relevancy['article_title'])

In [8]:
all_articles_relevancy

{'Intervention was the right thing to do': -128.5983496832,
 "SIX STATES FILE A CHALLENGE TO THE BIDEN ADMINISTRATION'S STUDENT LOAN CANCELLATION PROGRAM": 10.736387213661972,
 'Senator Reverend Warnock Introduces Bill to Ensure Georgia Car Buyers, Automakers Fully Benefit from Cost-Cutting Tax Credits': 24.818655258874706,
 '10 Markets Where Sellers Are Cutting Home Prices the Most': -72.32512534971688,
 'Biden touts Inflation Reduction Act, critics say student loan cancellation offsets gains': 5.265500967561742,
 'ULTIMUTT DEAL Aldiâ€™s new Â£40 Specialbuy item is perfect for dog owners': -31.900537619015694,
 "Students react to Biden's student debt relief plan": 36.243864645244216,
 "A GOP attorney general says people are 'celebrating prematurely' Biden's student-loan forgiveness, suggesting lawsuits are to come": -11.316006151600009,
 'Energy deal ban: Ofgem green lights major change for Brits - â€˜More resilient and fairâ€™': -133.98439525041726,
 'Couple who bought B&Q plant for just Â£12 discover its leaves are worth Â£170 each': -4.593019740318956,
 'Drivers face Â£35bn tax bill to plug the gap as switch to electric cars hits revenue': 9.789059342192678,
 'Sultan â€˜partnerâ€™ joins will battle': -4.709951949539176,
 'Press Release: California American Water Seeks Bill Relief for Customers Financially affected by COVID Pandemic': -83.24890318377042,
 'Tesco Bank to pay thousands of car insurance customers refunds after wide-spread policy error': -132.05658922885593,
 'Hickenlooper Cheers Record 200,000 Coloradans Enrolled for Health Insurance with Connect for Health; Sen. John W. Hickenlooper (D-CO) News Release': 51.19792404596613,
 'Boots announces big changes to Advantage Card club -and it means more discounts': -55.7808281814976,
 'Martin Lewis fan explains how he saved Â£400 after Virgin confirmed price hikes': -94.70934913920905,
 'Drivers at risk of Â£2,500 fine and three points for wiper blade error -how to check': -9.606121834150468,
 'How higher taxes on the rich could affect your investment goals and home prices surge 12% in February, the biggest jump since 2006': 36.696125032883394,
 'ANOTHER ROUND Sainsburyâ€™s is offering 25% off 6 bottles of prosecco, champagne and wine for bank holiday weekend': -71.43686170788405,
 'What happens when worker benefits are cut? Some suggest that workers offset benefit loss with more saving elsewhere; Evidence from state and...': 121.86104254699818,
 'SCAM ALERT: LOAN REPAYMENT COMPANIES SCAMMING STUDENTS, CHARGING THEM FOR SERVICES AVAILABLE FOR FREE': -37.759851788811105,
 'State Pension age changes could affect when you will be able to retire - check yours now': 74.30219383566242,
 'Biden Administration continues postponement of student loan debt payments for graduates': 28.43913609548739,
 'SWBC Approves Stadion Managed Account': 87.85390853823091,
 'Historic level of funding available to help clinicians pay off student loan': 56.30113203776112,
 "Chancellor announces 50% 'Eat Out to Help Out' discount for pub and restaurant meals during August": 14.391559058208019,
 'SAUCY SALES Lovehoney slashes 50% off sex toys for next two weeks as part of summer sale â€“ hereâ€™s what to buy': -60.14356354230247,
 'Workers facing a lifetime of playing pension catch-up': 115.28571394165611,
 'MENENDEZ WARNS OF IMPENDING EVICTION, FORECLOSURE CRISIS DUE TO COVID-19 PANDEMIC': 9.273276209877197,
 'State Pension: Can I retire at 60 and claim State Pension?': 129.77807234509294,
 'Sunwing offers long-awaited deals with significant savings on vacations at RIU Hotels & Resorts': -65.11401188650908,
 'What cinemas will look like after lockdown -with special areas for social bubbles': -50.98048550520933,
 'Anthropologie sale items are at a huge discount for Memorial Dayâ€”but not for long': -42.2336127636279,
 'Realtors demand looser mortgage rules; Also call on federal candidates to boost first-time buyers credit': -20.69648262742898,
 'Sharia bank Al Rayan launches a 1.6% easy access account less than a week after Marcus disappointed savers': -106.29680212258972,
 'Schiff Hardin Expands Estate Planning Practice With Ex-UBS Wealth Strategist': -35.27442109718883,
 'Waters Opening Statement at Hearing on Student Loan Debt Crisis; House Financial Services Committee News Release': 29.692712483138717,
 'New "Retire4Real" Online Game Will Help Teens Understand the Importance of Investing for Retirement': 196.22852077064928,
 "Landlords charge 'pet rent' to recoup losses after ban on unfair fees": 28.996070176646725,
 'Advice fees vary by 1,000 per cent': 30.659021686810277,
 'Super Saturday set to see Â£1.65billion blown on the high street before Christmas': -13.497741628282629,
 'BlackRock and Microsoft want to make retirement investing as easy as ordering an Uber': 38.9260966732084,
 'Canada pension fund investment into US detention firm larger than reported': -60.51172417780317,
 'Will Congress Update the Higher Education Act?(STATESTATS)': 11.166076059276293,
 "Can't afford kale and coconut water? Dietitian reveals the cheap, often-overlooked 'superfoods' that you can pick up at your local...": 33.66441653032971,
 'London stock market falls to 16-month low as trade war fears send the FTSE 100 index diving below 7,000': -82.42704915955406,
 "22 women honored for contributions; Peggy Ruhlin, Rianka Dorsainvil among InvestmentNews' Women to Watch": 34.742373847981405,
 "'eBay fraudster stole Â£1,023 and my gold coins but PayPal won't refund me'": 7.4482071931195115,
 'Draw up your will in a text message': 13.779426566057063,
 'Pension fund moves into riskier investments; Venture Capital': 31.219003433079045,
 'Equity release: read these top tips before you borrow against your home': 103.1979121401052,
 'Getting a loan is all about risk': 61.20367148693801,
 'Warning on rate hikes': 17.52541309564337,
 'Bank of England tightens mortgage borrowing rules amid fears of debt boom': -11.492842955300365,
 'Online firm pairs home buyers, sellers with realtors': -36.669162849631824,
 "Maternity leave - What happens if the baby's born early": 16.510417252882913,
 'Australia : New data highlights the flaws in failed VET FEE-HELP scheme': 44.20786154801679,
 'Bond fund warning as sell-off fears increase': -125.80638710746538,
 'Tax Talk Today Features IRS and Tax Pros Presenting, "Ready, Set, Retire! Helping Your Aging and Elderly Clients"': 53.11893200929679,
 'MARKET MOVERS THOMAS WELLS & PAUL PARASCANDALO': -143.1982352284709,
 'Residential Customers Seeing Lower Electric Bills Thanks to NatGas, EIA Says': -7.999881771981137,
 'Help clients get the most from Medicare: Retirement Scan': 99.94667788332956,
 'Landlords will face tougher tests from mortgage lenders': -17.171912028077774,
 'Long-term care delay post-fire frustrates seniors': 8.96838487335551,
 'Keys to keeping lid on spending': 40.92005077005033,
 'How Much Retirement Income Will You Need? Maybe Less Than You Think; New research calls the venerable 80% income-replacement rule into...': 173.55762529273267,
 'Health Care on a Budget': 116.29789247212697,
 "I'm a first-time buyer confused by mortgage options": 23.606216082147732,
 'Second Cup outlines 3-year turnaround plan amid $26.2M loss': -82.08054647822128,
 'Press Release: Aetna International Wins 2014 Health Insurance Award': -22.962205567457428,
 'Will apathy risks family losing their inheritance': -11.097117056614426,
 'New report reveals older worker hotspots and the vast differences in employment prospects for over 50s around the country': 62.42838230524094,
 'Drive a hard bargain; HAVE PASSPORT WILL TRAVEL Jeremy Gates rounds up all the latest travel news': -17.292091883825368,
 'A brighter future is now within reach; Workplace pensions Advertising Feature': 9.74776255145714,
 'Charge Cards vs. Debit Cards': 19.37923192229601,
 'New house sales build': -92.91324375574914,
 "Bonds Gain As Shutdown Intensifies Debt-Ceiling Fears -- Barron's Blog": -40.905102307419625,
 "Why divorce is bad for a man's health: Separation increases the risk of early death, substance abuse, suicide and depression": 34.433307466525356,
 'FEAR FOR ELDERLY WITH MORTGAGE DEBT': 55.37726543316538,
 "Don't be afraid to ask the difficult questions that come with retirement planning": 122.99501074984934,
 'A fund of one': -1.6268455536841837,
 'Compulsory pension for West workers': 75.17844103490832,
 'Three Tips For Building A Lasting Retirement': 158.05125349979065,
 'Certified COBRA Administrator COBRAGuard Inc. Awarded Contract with State of North Carolina': -4.139992464635737,
 "California's Brown signs pension bill, cites it as historic reform": 71.3705107551971,
 'Banking, Financial Services; Prudential reports higher rate taxpayers reject (GBP)438 million in tax relief': 89.84137234541942,
 'Grown-Up Spring Break Spots': 2.2057916877535897,
 "Should I use lump sum to pay off mortgage or save for children's studies?": 28.331521320574808,
 'New Book by Chicago Tax and Estate Planning Attorneys\xa0Reveals Disastrous Tax Pitfalls ; Cut Your Tax in 2010, by Anthony Perrelli and Dean...': -50.575016101148734,
 'YOUR MONEY BORROWING WATCH': 23.6050641490056,
 'Cloud of debt lifted through financial coaching program': -1.8264271724276044,
 'Labor helps union, nonunion jobless': 57.045318118713865,
 '8. Pay down debt': 21.282981673809175,
 'ETFs Finish Flat in Light Year-End Trading': -36.46535187508889,
 "Don't be too late": 129.12720983249807,
 'Consolidation loans - not the easy way out': 91.9740292076852,
 'Mortgage squeeze tightens after Abbey clamps down on interest-only deals': -67.15406337073092,
 'DOCTOR HAS CURE FOR TRAVEL SICKNESS ROW; ASK THE EXPERTS EDITED BY ABIGAIL MONTROSE': -37.93496542087226,
 'No margin for error...': -37.120737685681256,
 'Women still lack financial self esteem': 125.76633629716562,
 'BORROWERS TOLD TO ACT FAST OVER MORTGAGES': -120.62610529963496,
 'Dividing the spoils': 37.119210656679115,
 'SECOND-CHANCE INVESTING': -85.77024956844095,
 "COMMENT: It's tough to justify 10-year fixes": -56.1696127660655,
 'Offshore bonds better onshore counterparts bob goulding | Clerical Medical': -156.72962831277357,
 'Money Management: Keeping it in the family.': 8.452503104088814,
 'Some banks offer reward points for debit card use': -132.10682678105763,
 'Personal Business: OK, if I Just Pay the Card Minimum. . .Ouch': 27.22244582399002,
 'Wealth: What you can learn from the big-money investors': -1.4650807475028653,
 "Planner: Turn portfolio to more conservative path ; Without a secure job, it's important to tone down risk": 35.17845573699439,
 "Portman: Hasn't Received Any Takeover Approaches": -81.21384844382736,
 "Harsco Had Expected To Contribute $24M To Pension In '04": -59.08656117051311,
 'Mail Money - MONEY BOX.': 37.77389036720726,
 'Street Smart: Economy Watch -- Inflation Is Worse Than You Thought --- If the CPI does not reflect the true cost of living, your retirement...': 53.716788339183296,
 'Teachers blasts Caisse loophole': 3.327617345647925,
 'SL venture capital firm creates list of top tech, biotech leaders': -39.95888479967826,
 "Hercules Sees Asbestos-Related Payments $40M-$45M In '04": -0.5544014293037298,
 'Mad Cow Disease Risk Sparks Call For Wider Import Ban': -26.373643398284912,
 'The Life Mag - Money Matters - Dodging undue death duties.': -8.101574167624197,
 'Personal Finance - Drop in the ocean of with-profit policies.': -51.06960930879228,
 'Rate cut may remind some homeowners to refinance.': -73.56307651288267,
 'Jobs & Money - Women stand to get a better deal.': 76.61439081589491,
 'Pension off AVC rules; The Last Word': -25.96770823019045,
 'Gold Stocks Favoured As Telecom, Bank Shares Fall': -166.52227190795702,
 "Wall of silence over 'flexible' Abbey fund": -8.186077161781187,
 'Million-dollar Partners': 44.02029246024705}

In [18]:
for key in all_articles_relevancy.keys():
    if all_articles_relevancy[key] < 0:
        articles_df.loc[articles_df['article_title'] == key, ['predicted']] = 0

pd.set_option('display.max_rows', 1000)
articles_df[['relevant_campbell', 'predicted']]

     relevant_campbell  predicted
0                    0        0.0
1                    0        1.0
2                    1        1.0
3                    1        0.0
4                    0        1.0
5                    0        0.0
6                    1        1.0
7                    0        0.0
8                    0        0.0
9                    0        0.0
10                   1        1.0
11                   0        0.0
12                   1        0.0
13                   0        0.0
14                   1        1.0
15                   0        0.0
16                   0        0.0
17                   0        0.0
18                   1        1.0
19                   0        0.0
20                   1        1.0
21                   1        0.0
22                   1        1.0
23                   1        1.0
24                   0        1.0
25                   1        1.0
26                   1        1.0
27                   0        0.0
28                   1        1.0
29                   1        1.0
30                   1        1.0
31                   0        0.0
32                   0        0.0
33                   0        0.0
34                   1        0.0
35                   0        0.0
36                   0        0.0
37                   1        1.0
38                   1        1.0
39                   1        1.0
40                   1        1.0
41                   1        0.0
42                   1        1.0
43                   0        0.0
44                   0        1.0
45                   1        1.0
46                   0        0.0
47                   0        1.0
48                   1        1.0
49                   0        1.0
50                   0        1.0
51                   1        1.0
52                   1        1.0
53                   1        1.0
54                   0        0.0
55                   0        0.0
56                   1        1.0
57                   1        1.0
58                   0        0.0
59                   1        1.0
60                   0        0.0
61                   1        0.0
62                   1        1.0
63                   1        0.0
64                   1        1.0
65                   1        1.0
66                   1        1.0
67                   1        1.0
68                   1        1.0
69                   0        0.0
70                   0        0.0
71                   1        0.0
72                   1        1.0
73                   0        0.0
74                   0        1.0
75                   1        1.0
76                   0        0.0
77                   0        0.0
78                   1        1.0
79                   1        1.0
80                   1        1.0
81                   0        0.0
82                   1        1.0
83                   1        1.0
84                   0        0.0
85                   1        1.0
86                   1        1.0
87                   0        1.0
88                   1        1.0
89                   0        0.0
90                   0        1.0
91                   1        0.0
92                   1        1.0
93                   1        1.0
94                   0        0.0
95                   1        1.0
96                   1        1.0
97                   0        0.0
98                   0        0.0
99                   0        0.0
100                  1        1.0
101                  1        0.0
102                  1        1.0
103                  0        0.0
104                  0        0.0
105                  0        0.0
106                  1        1.0
107                  0        0.0
108                  1        1.0
109                  1        0.0
110                  1        1.0
111                  0        0.0
112                  0        0.0
113                  1        1.0
114                  1        1.0
115                  0        1.0
116                  0        0.0
117                  0        0.0
118                  0        0.0
119                  1        0.0
120                  1        0.0
121                  1        0.0
122                  1        1.0
123                  0        0.0
124                  0        0.0
125                  0        0.0
126                  1        1.0

In [20]:
num_ers = 0
true_positive = 0
true_negative = 0
false_positive = 0
false_negative = 0

for index, row in articles_df.iterrows():
    
    if row['relevant_campbell'] == 1:
        
        if row['predicted'] == 1:
            true_positive += 1
        
        if row['predicted'] == 0:
            false_negative += 1
    
    if row['relevant_campbell'] == 0:
        
        if row['predicted'] == 0:
            true_negative += 1
            
        if row['predicted'] == 1:
            false_positive += 1
        
    
    if row['relevant_campbell'] != row['predicted']:
        num_ers += 1

eval_dict = {}

print(f"True positive = {true_positive}")
print(f"True Negative = {true_negative}")
print(f"False_negative = {false_negative}")
print(f"False_positive = {false_positive}")
print(f"Total number of errors = {num_ers}/127")
eval_dict['true_positive'] = true_positive
eval_dict['true_negative'] = true_negative
eval_dict['false_positive'] = false_positive
eval_dict['false_negative'] = false_negative
eval_dict['accuracy'] = (true_positive+true_negative)/(true_positive+true_negative+false_negative+false_positive)
eval_dict['precision'] = true_positive / (true_positive + false_positive)
eval_dict['recall'] = true_positive / (true_positive + false_negative)
eval_dict['f1_score'] = (2 * eval_dict['precision'] * eval_dict['recall']) / (eval_dict['precision'] + eval_dict['recall']) 
#print(f"correctly_classified documents  = {correctly_classified}")
print(f"Accuracy = {eval_dict['accuracy']}")
print(f"Precision = {eval_dict['precision']}")
print(f"Recall = {eval_dict['recall']}")
print(f"F1-Score = {eval_dict['f1_score']}")

eval_df = pd.DataFrame (pd.Series(eval_dict)).T
#eval_df.to_csv('results/'+model_name+'/'+model_name+'_metrics.csv')

True positive = 55
True Negative = 47
False_negative = 14
false_positive = 11
Total number of errors = 25/127
Accuracy = 0.8031496062992126
Precision = 0.8333333333333334
Recall = 0.7971014492753623
F1-Score = 0.8148148148148148